### PR TITLE
Feature nav bar

### LINKED ISSUE #2: Feature: Navigation bar

### PR DESCRIPTION
**Pull request by chisafukutome**

### CODE REVIEW

**Comment by aatng-gh** [comment]
@chisafukutome you want to merge into `main`?

**Review by jparedes-io — COMMENTED** [review]
Let's merge to the `dev` first!

**Comment by chisafukutome** [comment]
> @chisafukutome you want to merge into `main`
Oops. I meant for the 'dev' branch. Can I change? or I need to request again with 'dev' setting?

**Comment by jparedes-io** [comment]
All good, sounds like a plan .

**Review by aatng-gh — APPROVED** [review]
LGTM!

**Pull request merged**
